"""Generate frontend/lib/skills.ts from the canonical skill manifest.

Reads ~/workspace/skill-library/dist/manifest.json (369 skills) and emits a
typed TS module: Skill type, SKILLS array, CATEGORIES, CATEGORY_META
(icon + color scheme per category), and FEATURED_SKILLS (8 spanning categories).
"""
import json
import os

MANIFEST = "/home/hatch/workspace/skill-library/dist/manifest.json"
OUT = "/home/hatch/workspace/skillco/frontend/lib/skills.ts"

CAT_LABELS = {
    "ai-agents": "AI Agents",
    "dev-tools": "Dev Tools",
    "music": "Music",
    "n8n/automation": "Automation",
    "prospecting/GTM": "Prospecting",
    "data": "Data",
    "other": "Other",
}

# icon component name (from @phosphor-icons/react), gradient, border
CAT_STYLE = {
    "AI Agents": ("Robot", "from-blue-500/20 to-blue-600/20", "border-blue-500/30"),
    "Dev Tools": ("Code", "from-cyan-500/20 to-cyan-600/20", "border-cyan-500/30"),
    "Music": ("MusicNotes", "from-purple-500/20 to-purple-600/20", "border-purple-500/30"),
    "Automation": ("Lightning", "from-orange-500/20 to-orange-600/20", "border-orange-500/30"),
    "Prospecting": ("MagnifyingGlass", "from-rose-500/20 to-rose-600/20", "border-rose-500/30"),
    "Data": ("Database", "from-amber-500/20 to-amber-600/20", "border-amber-500/30"),
    "Other": ("FileText", "from-teal-500/20 to-teal-600/20", "border-teal-500/30"),
}


def title_case(slug: str) -> str:
    return " ".join(w[:1].upper() + w[1:] for w in slug.split("-") if w)


def trunc(s: str, n: int = 180) -> str:
    s = " ".join(s.split())
    return s if len(s) <= n else s[: n - 1].rstrip() + "…"


def ts_str(s: str) -> str:
    return json.dumps(s, ensure_ascii=False)


def main() -> None:
    manifest = json.load(open(MANIFEST, encoding="utf-8"))
    assert len(manifest) == 369, f"expected 369, got {len(manifest)}"

    skills = []
    for m in sorted(manifest, key=lambda x: x["name"]):
        label = CAT_LABELS[m["category"]]
        skills.append({
            "id": m["name"],
            "name": title_case(m["name"]),
            "description": trunc(m["description"] or ""),
            "category": label,
            "version": m.get("version", "1.0.0"),
            "price": "Free",
            "platform": "Universal",
            "installs": 0,
            "rating": 5.0,
        })

    categories = sorted({s["category"] for s in skills},
                        key=lambda c: list(CAT_LABELS.values()).index(c))

    # featured: first (alphabetical) skill of each category + one extra AI agent
    by_cat = {}
    for s in skills:
        by_cat.setdefault(s["category"], []).append(s["id"])
    featured = [by_cat[c][0] for c in categories]
    featured.append(by_cat["AI Agents"][1])

    icons_used = sorted({CAT_STYLE[c][0] for c in categories})

    lines = []
    lines.append('// AUTO-GENERATED by frontend/scripts/generate-skills-lib.py')
    lines.append('// Source: skill-library/dist/manifest.json — 369 canonical skills.')
    lines.append('// Do not edit by hand; re-run the generator.')
    lines.append('')
    lines.append('import {')
    lines.append('  ' + ',\n  '.join(icons_used) + ',')
    lines.append('  type Icon,')
    lines.append('} from "@phosphor-icons/react";')
    lines.append('')
    lines.append('export interface Skill {')
    lines.append('  id: string;')
    lines.append('  name: string;')
    lines.append('  description: string;')
    lines.append('  category: string;')
    lines.append('  version: string;')
    lines.append('  price: "Free" | "Paid";')
    lines.append('  platform: string;')
    lines.append('  installs: number;')
    lines.append('  rating: number;')
    lines.append('}')
    lines.append('')
    lines.append('export interface CategoryMeta {')
    lines.append('  icon: Icon;')
    lines.append('  color: string;')
    lines.append('  borderColor: string;')
    lines.append('}')
    lines.append('')
    lines.append('export const CATEGORIES: string[] = [')
    for c in categories:
        lines.append(f'  {ts_str(c)},')
    lines.append('];')
    lines.append('')
    lines.append('export const CATEGORY_META: Record<string, CategoryMeta> = {')
    for c in categories:
        icon, color, border = CAT_STYLE[c]
        lines.append(f'  {ts_str(c)}: {{ icon: {icon}, color: {ts_str(color)}, borderColor: {ts_str(border)} }},')
    lines.append('};')
    lines.append('')
    lines.append('export const SKILLS: Skill[] = [')
    for s in skills:
        lines.append('  {')
        lines.append(f'    id: {ts_str(s["id"])},')
        lines.append(f'    name: {ts_str(s["name"])},')
        lines.append(f'    description: {ts_str(s["description"])},')
        lines.append(f'    category: {ts_str(s["category"])},')
        lines.append(f'    version: {ts_str(s["version"])},')
        lines.append(f'    price: {ts_str(s["price"])},')
        lines.append(f'    platform: {ts_str(s["platform"])},')
        lines.append(f'    installs: {s["installs"]},')
        lines.append(f'    rating: {s["rating"]},')
        lines.append('  },')
    lines.append('];')
    lines.append('')
    lines.append('export const FEATURED_SKILL_IDS: string[] = [')
    for fid in featured:
        lines.append(f'  {ts_str(fid)},')
    lines.append('];')
    lines.append('')
    lines.append('export const FEATURED_SKILLS: Skill[] = FEATURED_SKILL_IDS.map(')
    lines.append('  (id) => SKILLS.find((s) => s.id === id),')
    lines.append(').filter((s): s is Skill => s !== undefined);')
    lines.append('')

    os.makedirs(os.path.dirname(OUT), exist_ok=True)
    with open(OUT, "w", encoding="utf-8") as f:
        f.write("\n".join(lines))
    print(f"wrote {OUT} ({len(skills)} skills, {len(featured)} featured)")


if __name__ == "__main__":
    main()
